### ISSUE TITLE
Bug at Multi-Language Support

### ISSUE THREAD

**Issue by ianeinser** [openware/postmaster#16]
Hi @shal ,
may i know how to set usr.Language? because i got error reported that Language is not supported. Where should i set it? it is an optional fied when user signs up. Thus may i suggest if you use EN as default if language field is empty

**Comment by shal** [comment]
Hi @ianeinser, 

Yeah, we will add tiny doc about how multi language support works.

For now I make a short overview:
Postmaster has configuration file with list of languages and templates.

Here is [default](https://github.com/openware/postmaster/blob/master/config/postmaster.yml) configuration.

**Note:** Ensure that your barong it up to date. Postmaster required language field in event API payload

To add new language you need:
-  Add new languages to the list of languages. 
https://github.com/openware/postmaster/blob/79db3f1aec253fd0a87c593b430f4269809fffa8/config/postmaster.yml#L5-L9
- For each event add template with email in this language.
https://github.com/openware/postmaster/blob/79db3f1aec253fd0a87c593b430f4269809fffa8/config/postmaster.yml#L12-L29

**Comment by dunklestar** [comment]
Hi @shal , 

Thanks for the reply. I pulled the latest Barong and tried it before opening the issue. It seems that Barong master branch doesnt include the language field yet. Besides the field is still optional and left empty. What do you decide in the unmarshal function when the field is empty? I suppose that you reports error for the empty field. Here are the payload 

`D, [2019-04-15T09:05:50.420689 #1] DEBUG -- : 
Produced new event at 2019-04-15 09:05:50 UTC: 
name    = system.user.email.confirmation.token
payload = {"payload":"eyJpc3MiOiJiYXJvbmciLCJqdGkiOiJjZmMxNzA0MS00ZjdlLTRmNjAtODdlMi05MTQzZjQyMTdlNWUiLCJpYXQiOjE1NTUzMTkxNTAsImV4cCI6MTU1NTMxOTIxMCwiZXZlbnQiOnsidXNlciI6eyJ1aWQiOiJJRDg1NzM3RTkzODAiLCJlbWFpbCI6Imlhbi5laW5zZXJAb3V0bG9vay5jb20iLCJyb2xlIjoibWVtYmVyIiwibGV2ZWwiOjAsIm90cCI6ZmFsc2UsInN0YXRlIjoicGVuZGluZyIsImNyZWF0ZWRfYXQiOiIyMDE5LTA0LTE1VDA5OjA1OjUwWiIsInVwZGF0ZWRfYXQiOiIyMDE5LTA0LTE1VDA5OjA1OjUwWiJ9LCJsYW5ndWFnZSI6bnVsbCwiZG9tYWluIjoiY2hhbmdlbWUuY29tIiwidG9rZW4iOiJleUpoYkdjaU9pSlNVekkxTmlKOS5leUpwWVhRaU9qRTFOVFV6TVRreE5UQXNJbVY0Y0NJNk1UVTFOVE15TlRFMU1Dd2ljM1ZpSWpvaVkyOXVabWx5YldGMGFXOXVJaXdpYVhOeklqb2lZbUZ5YjI1bklpd2lZWFZrSWpwYkluQmxZWFJwYnlJc0ltSmhjbTl1WnlKZExDSnFkR2tpT2lJeVlUVmpOelUxTXpRMllUaGxaakE1WldJM01DSXNJbVZ0WVdsc0lqb2lhV0Z1TG1WcGJuTmxja0J2ZFhSc2IyOXJMbU52YlNJc0luVnBaQ0k2SWtsRU9EVTNNemRGT1RNNE1DSjkuaV85NmhxN3pHdmVNalNhMlo2NEExVFNTRGRSVHNDbG4tSVkzUGRHZWlDWGxiYVVVZGpuMmFpaENUc2hRZ1V4SUcwT1pkQW1uU2VORDNNTHlyazZnS3JHWUVHUThDS1dyZUhnaVhYRVJfQjdxRkpiM2tScDRfd3RneEdkNWVyaW1McUltWFZTVEg2MDVWRUJXNTkxeWhCYWJXdkZKb1BFUEFyU1pveVdETE5yTVltanY4bEtrdUNPZ0o3T29TSXRiYVNtQlNVVzVySWRIUTkwdGVQa1l2TTM0Y2JwNnZLVWVhM0FyU0d1bDgyUThFMHdLWS1IcFJ6U1otbGNuRVdtSDdCZXNYbVQyQnFyeXJ4SDdRWEF6Z0VTdmFSbmJJdS1XOWNTY1dsbVVZZ0U0bGo0d0RoU2J5WkNCeGVzdVFBTllDeUVIZHVNaDA4eEVmeGNTeF9jMGZ3IiwibmFtZSI6InN5c3RlbS51c2VyLmVtYWlsLmNvbmZpcm1hdGlvbi50b2tlbiJ9fQ","signatures":[{"protected":"eyJhbGciOiJSUzI1NiJ9","header":{"kid":"barong"},"signature":"RGpCGHtulKkiwyCO6KB7XmxFdT_28-4jb48OOct8Y2UFUnUQXlwI_dkYnb5WRkUNvLLupDRWHMWFUpEskAWzfhbE34Z5ppVimpCcrzHur6b8un68ZpCZjT6leyAdyviChEMu--MkFIQm1YuRZBNjZIMLEcLu9lWwTG_8XZ6HGDfYvPr5XKN9YbtrV1_vNnbAWlD9fN0VNZoVoIaQjYbxriuAH0i-IiJXaDY4y7hscMn2I4USar1Kzx0k8gVYJRIay7aHlLwSnRSPfZEzhnZkmWgrK_TYYFqPUs7hMvpnLFJxR5TCZN4rR9C8VoR6pzIXGwTdD_IXnAhqomm8BymWwA"}]}
`

**Comment by ianeinser** [comment]
Hi @shal ,

i use the latest Barong master branch before opening the issue. It seems even the latest Barong leaves the language field empty. I suppose that the unmarshal function reads empty field and reports it as error instead of using EN as default templates.

**Comment by shal** [comment]
In this case I think you need to create issue in Barong :)

**Comment by ianeinser** [comment]
Yeah.. i am also confused because lang is an optional field in Barong but a mandatory in Postmaster.

https://github.com/rubykube/barong/blob/master/app/api/v2/identity/users.rb

please check it out

**Comment by shal** [comment]
@ianeinser

As far as I know barong always send some value in language field in the payload.

By default language equals `"en"`. In case language is defined in API parameter it send it to postmaster.

For more questions contact @ec, he is responsible for barong
