### ISSUE TITLE
Bug at NewEmailSender function 

### ISSUE THREAD

**Issue by ianeinser** [openware/postmaster#18]
Hi @mod @shal ,
I found a bug. Here is what i did. we pulled the latest postmaster, namely v0.0.13. Then we tried and check sendgrid dashboard, nothing was forwarded to sendgrid. Then we use debugger to check and found that postmaster stucks at this line and cannot pass the function call NewEmailSender.

`if err := NewEmailSender(conf, email).Send(); err != nil {
				log.Println(err)
}
and then it reported 
2019/04/17 01:20:03 dial tcp 167.89.115.53:25: connect: connection timed out
`

we thought we may do wrong but then we use the postmaster docker image v.0.0.4. It works, sendgrid was able to receive and to forward to user email.

**Comment by ianeinser** [comment]
Hi @shal ,

have you found and solved the bug? Will you accept PR?

**Comment by shal** [comment]
@ianeinser Hi, thats interesting. Could you post your config?

**Comment by shal** [comment]
Closing, because of inactivity.
